name: Docker Checks

on:
  workflow_dispatch:
  push:

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  COMPOSE_FILE: docker-compose.ci.yml
  # It counts some attestation etc packages, each commit gives 3 pckages
  OLD_VERSIONS_TO_KEEP: 75 # 25 commits
  DOCKER_BUILD_CHECKS_ANNOTATIONS: false

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          ignore: DL3006

      - name: Read .ruby-version
        id: ruby-version
        run: echo "ruby-version=$(cat .ruby-version)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ci
          # Used by docker-compose.ci
          tags: image_ci:latest
          build-args: |
            RUBY_VERSION=${{ steps.ruby-version.outputs.ruby-version }}

      - name: Run Bundle Audit
        run: |
          docker compose run --rm app sh -c 'bundle audit'

      - name: Run Rubocop
        run: |
          docker compose run app rubocop

  push_production:
    permissions:
      contents: read
      packages: write
    needs:
      - tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # full length sha
            type=sha,format=long,prefix=
          flavor: |
            latest=true

      - name: Read .ruby-version
        id: ruby-version
        run: echo "ruby-version=$(cat .ruby-version)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          target: live
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=live           # scope=<scope>: which scope cache object belongs to (default buildkit)
          cache-to: type=gha,mode=max,scope=live
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_CODE_VERSION=${{ github.sha }}
            RUBY_VERSION=${{ steps.ruby-version.outputs.ruby-version }}

      - name: Delete old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: "container"
          min-versions-to-keep: ${{ env.OLD_VERSIONS_TO_KEEP }}
